### ISSUE TITLE
test-support should not be available as a feature flag

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#116]
For better or worse, this makes it part of the public API.

**Comment by hawkw** [comment]
@carllerche What do you suggest as an alternative? I'd like to be able to use the test-support code in multiple crates (it's currently used for testing `-futures`), and I'm not sure how to share it while still allowing the crates to be published to crates.io eventually.

**Comment by carllerche** [comment]
It depends on the exact goals trying to be achieved. If it is for internal testing, one strategy would be to create a "shadow" crate in the git repo. A new `Cargo.toml` as well we a `build.rs` file that emits a cfg flag. Then use the `path` mod attribute to load the main source.

Dependencies in the crate can use that shadow crate.
