### ISSUE TITLE
Support methods of serializing/formatting field values other than `Debug`

### ISSUE THREAD

**Issue by hawkw** [hawkw/tokio-trace-prototype#12]
Right now, field values are represented by `dyn Value`, where `Value` is a trait that essentially aliases `fmt::Debug + Send + Sync`. This means that we can basically only format values with the debug formatter, which is not great.

We should be able to support serializing value types with other serializers, such as `fmt::Display` and `serde`, when these are available.

I think the right thing to do here is to change values to something like `Any`, so that subscribers can try to downcast them as implementors of traits like `fmt::Debug` and `serde::Serialize`?

**Comment by davidbarsky** [comment]
> I think the right thing to do here is to change values to something like Any, so that subscribers can try to downcast them as implementors of traits like fmt::Debug and serde::Value?

Yep! I think an open question would be what to do with regard to error handling if a value fails to be serialized, but that might need to be handled by individual subscribers. I'm still kinda split as to that they should do. Panicking _might_ be justifiable, in that's non-recoverable error, but so would silently failing—operators would not see data on their system.

What do you think?

**Comment by hawkw** [comment]
I don't think using `Any` will work here. I had forgotten that `Any` can only be downcast to _concrete_ types --- i.e., we can't downcast to trait objects like `dyn fmt::Display` or `dyn serde::Serialize`. I think if we want to support `serde`, we'll have to use an approach where it's in the `tokio_trace` core library and feature-flagged so it can be disabled, which is a shame.

**Comment by hawkw** [comment]
@davidbarsky 
> what to do with regard to error handling if a value fails to be serialized, but that might need to be handled by individual subscribers. 

I think that's going to have to be up to the subscriber implementation.
