### ISSUE TITLE
Remove `Callsite::interest`

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#120]
I don't see a reason to have this on the trait.

Depends on #111.

**Comment by hawkw** [comment]
I'm not sure if I understand how this would be possible. Even if we move the `Span` type out of `-core`, as #111 suggests, there still needs to be some way to get the current interest from a callsite? Otherwise, how would we know whether a user implementation of `Callsite` is enabled?

**Comment by carllerche** [comment]
The callsite itself is the only thing that should care of it is enabled or not. That makes the logic private to the callsite and does not need to be part of the trait IMO.

**Comment by hawkw** [comment]
@carllerche Yeah, you're right --- if `Span::new_disabled` is public API, then the callsite can be responsible for deciding if the current interest means that it should call `Span::new` or `Span::new_disabled`. We can then remove the `interest` accessor.
