### ISSUE TITLE
Subscriber should have a `record_unknown` fn as a catch all

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#125]
This allows signalling to the subscriber that a type unknown to the subscriber has been provided. In the future, `Subscriber` will gain additional `record` fns that will default to forwarding to this `unknown` fn.

**Comment by hawkw** [comment]
@carllerche Currently, all the `Subscriber::record_$TYPE` functions for primitive types default to calling `record_fmt`, do you think that these should be changed to default to `record_unknown` instead? 

This would require most subscriber implementations to override these defaults if they want to format most values, when they currently do not need to override these functions.

**Comment by carllerche** [comment]
I still have to think more about `record_fmt`...

Long term, not all values will impl `Debug`.

**Comment by carllerche** [comment]
The question is, should `record_unknown` have a default implementation or not? If the answer is no, then we need to add it now.

**Comment by hawkw** [comment]
I've [closed](https://github.com/hawkw/tokio-trace-prototype/pull/134#issuecomment-443311964) PR #134, which added this method, for the following reason:
> After talking it over a bit more with @carllerche this morning, we determined that it's probably better to _not_ move forward with this PR, and continue falling back to `Debug` as we are currently. The assumption that all future `Value` types will implement `Debug` seems acceptable. 
>
> To make this a bit clearer, I'll be replacing the `record_fmt` method, which accepts an arbitrary `fmt::Arguments`, with a `record_debug` function. If there's demand for recording `Display` values, we can always add a `record_display` later.

**Comment by hawkw** [comment]
I meant to close this issue in #153; closing it now.
