### ISSUE TITLE
In -core, `span::Id` should probably just be named `Span`.

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#126]
Since there is no more differentiating between a span and the identifier. The type probably makes more sense named "Span".

**Comment by hawkw** [comment]
Yeah, I was considering that as well. I'm not sure how I feel about `tokio-trace` re-exporting the type under a different name, though, that seems potentially confusing.

**Comment by davidbarsky** [comment]
> I'm considering one of two naming options (open to bikeshedding though):
> - tokio-trace re-exports core::Span as span::Id
> - tokio-trace re-exports core::Span as Span, renametokio-trace::span::Span to Handle (or SpanHandle)

I like the first option, especially given that Tokio is moving away from the whole “Handle” nomenclature in public APIs (as best I can tell).

@hawkw

**Comment by carllerche** [comment]
@hawkw my assumption is that tokio-trace *would not* re-export `core::Span`. Instead, it would newtype as needed.

**Comment by hawkw** [comment]
@carllerche that's also a reasonable option! I was just thinking that you ought to be able to implement a `Subscriber` with a dependency on just `tokio-trace` without an _explicit_ dependency on `tokio-trace-core`, and so all the types that are mentioned in the `Subscriber` method signatures ought to be re-exported. WDYT?

**Comment by carllerche** [comment]
My assumption is that subscriber implementations would depend on Tokio-Trace-subscriber or on -core. Tokio-Trace would be for libs and applications. 

Not entirely sure though, I haven’t thought in depth about it.

**Comment by hawkw** [comment]
@carllerche Okay, that makes sense to me --- part of why I thought one would want to just use the `tokio-trace` crate for implementing `Subscriber`s is that the `tokio-trace-subscriber` currently needs a lot more work, but eventually I agree that it ought to be the expected way to write `Subscriber`s for sure.
