### ISSUE TITLE
There should be an opaque struct representing a set of fields

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#130]
Instead of using `&[&str]`, we probably should have a `Fields` struct. `Metadata` would then have `&'static Fields` to reference those fields.

The misc fns to work with fields can be moved to that struct.

**Comment by hawkw** [comment]
@carllerche I agree that this is probably a good idea.

As far as I can tell, though, if this type is to be constructed statically (i.e. by the `metadata!` macro), it will have to have `#[doc(hidden)] pub` fields, at least until `const fn` is stable. In your opinion, is it acceptable to add another type with `#[doc(hidden)]` public fields?

**Comment by carllerche** [comment]
@hawkw Yes, that strategy is correct. At some point in the future we can switch to const fn, but a macro will do for now w/ `doc(hidden)` fields.
