### ISSUE TITLE
Why is Key::as_usize public?

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#141]
The fact that Key can be represented as a `usize` feels like a private implementation detail.

**Comment by hawkw** [comment]
Yeah, the intention behind this was for it to be used as part of an earlier scheme for field values, where `Value`s were stored in an array, and the `as_usize` function was used to index that array. With the current `record`-based value interface, this is no longer necessary, so I think this function can be completely removed.

**Comment by hawkw** [comment]
This was closed by #152, but I must've forgotten to tag it.
