### ISSUE TITLE
Regarding: // TODO: can this just be public API?

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#145]
If they don't have to be public, they shouldn't be public!

If we can ship with `Callsite::id` and `Identifer::from_callsite` both being private, great.

**Comment by hawkw** [comment]
Okay, fair enough! The comment was mainly that I couldn't _immediately_ come up with a reason for those functions to be public, but I figured there might be a use-case for them that I was overlooking. Will remove the comments for now :)
