### ISSUE TITLE
Constructor macros (like meta!) should be in -core

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#150]
The macro needs to be able to be updated in step with the struct fields.

Ideally, this macro would be minimal and stick to named arguments...

```rust
static MY_META: Meta = metadata!(name: "foo", file: file!(), ...)
```

**Comment by hawkw** [comment]
I've opened PR #155 to add a `metadata!` macro like this in `core`. @carllerche, do you think this is sufficient, or would you like the `callsite!` macro moved into `core` as well? Right now, that macro (which exists primarily to factor out common code between the `span!` and `event!` macros) is more than just a simple constructor...

**Comment by carllerche** [comment]
IIRC, `callsite!` does not need to as it does not construct any structs that are defined in `-core`.

**Comment by hawkw** [comment]
Okay, thanks, just making sure.
