### ISSUE TITLE
Split `tokio-trace` into `tokio-trace` and `tokio-trace-core`

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#23]
The absolute minimum that is required to power to power the tracing infrastructure should be in `tokio-trace-core`. This crate will need to remain as stable as possible.

Macros, helpers, etc... can go in `tokio-trace`.

**Comment by hawkw** [comment]
> The absolute minimum that is required to power to power the tracing infrastructure should be in `tokio-trace-core`. 

Agreed. This will definitely be necessary to go from a prototype to something that's ready for release. I've made a [v0.1 milestone](https://github.com/hawkw/tokio-trace-prototype/milestone/1) to track the changes that are part of that process.

**Comment by hawkw** [comment]
#22, #33, and #41 represent a start on this --- the current `tokio-trace` crate is pretty close to becoming `tokio-trace-core`. The batteries-included facade crate will need to be added.

**Comment by carllerche** [comment]
* Macros should not be part of the core crate.
* The core crate should not depend on `futures` (ideally no deps).
