### ISSUE TITLE
Questions on Marking Events as ”Done”

### ISSUE THREAD

**Issue by davidbarsky** [hawkw/tokio-trace-prototype#4]
Something I noticed that made implementing a slog subscriber a bit tricky is that the `Event` struct lacks a method to mark itself (and all child spans) as “done”. This means that a Subscriber might see various children of a single span, making it necessary for event reconstruction to occur on the subscriber via a recursive walk up a tree of events/spans. I think the ergonomics of implementing a subscriber can be improved by two things: 

- Sending _only_ the root span/event to a subscriber.
- Creating an enum called `CompletionState` (bikeshedable name) that tracks whether a span/enum has completed. If a parent span is marked as done, all child spans are _also_ marked as done. I'm thinking at an event will _only_ be send to a subscriber if the top-level (i.e., `SpanInner.parent` is `None`) span is marked as done.

A small thing—I think I'm confused between events and spans. Would be nice to _maybe_ unify on terminology.

For prior work, see [OpenCensus](https://github.com/census-instrumentation/opencensus-go/blob/master/trace/trace.go#L245) with regard to marking spans/events/traces as “done“.

**Comment by hawkw** [comment]
I completely agree that we need a way to mark spans as having finished or completed. I think that this may be as simple as adding a boolean flag on the `Subscriber::exit` method that's called when the program exits from a given `Span` --- call it `is_done` or `is_final`, perhaps. This flag would indicate that the span in question has completed and will not be entered again over the course of the program's lifetime.

Regarding your other comments:
>  If a parent span is marked as done, all child spans are also marked as done. 

The way I think of parent and child spans treats this relationship as implicit --- a parent span is not allowed to complete until all of its children have already completed. Future work will introduce the concept of a span _following from_ (i.e. being conceptually linked to) other spans from which it is not directly linked, but the parent-child relationship as I've written it is intended to indicate that the parent is essentially _comprised of_ its children.

> Sending only the root span/event to a subscriber [...]

This implies a misunderstanding of the way the prototype is currently implemented: at the moment, there is an implicit root span which _all_ other spans are the children of:
https://github.com/hawkw/tokio-trace-prototype/blob/0cddea3ba847d2a50ffa53f913e60cf43609b7fa/tokio-trace/src/lib.rs#L71-L85

This was added primarily for ease of implementation, but if you think this is incorrect behaviour, it can be removed. That way, events such as new requests entering the system could perhaps be associated with their own unique trees more readily?

> A small thing—I think I'm confused between events and spans. Would be nice to maybe unify on terminology.

You may appreciate knowing that I've started trying to add some docs to make the terminology a bit clearer: https://github.com/hawkw/tokio-trace-prototype/commit/b8c5180caf5811547a2a89858912c263abf3eba7

**Comment by hawkw** [comment]
> Nice! To bikeshed the name, it could maybe be an enum, not a boolean.

I'm open to using an enum rather than a boolean --- I do want to avoid causing ["boolean blindness"](https://existentialtype.wordpress.com/2011/03/15/boolean-blindness/). In this case, I felt like for a simple, two-value argument with no fields, it was easier to be able to say 
```rust
if is_final {
    // ...
}
```
than
```rust
if completion == CompletionState::Final {
    // ...
}
```
or something similar, but again, I'm not attached to using a bool here...

**Comment by davidbarsky** [comment]
Yeah, for some reason I though an enum variant could deref'd to a boolean.
Booleans are fine!

**Comment by hawkw** [comment]
@davidbarsky I've started looking into this, and I think we may end up going a different route --- I realized that spans _can_ know their own state if we update it atomically. So there may end up being a span state enum after all :)

**Comment by davidbarsky** [comment]
@hawkw Oh okay doke!

**Comment by davidbarsky** [comment]
That looks great! When you mean the logic—can you elaborate?

**Comment by hawkw** [comment]
@davidbarsky I've opened  #10 to track getting rid of the implicit root span, which seems like a different issue.
