### ISSUE TITLE
What is the intent of the `tokio_trace::span::State` enum?

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#57]
I'm not following why this is provided by the core crate.

**Comment by hawkw** [comment]
Its main purpose is to distinguish between when a span is exited but will be entered again, and when a span has completed. This is in core because it seems like something that all subscribers would want to be informed of.

**Comment by hawkw** [comment]
I'm in the process of removing the `State` enum in [a branch](https://github.com/hawkw/tokio-trace-prototype/tree/eliza/slice-n-dice) and replacing it with a separate `Subscriber::close` function.
