### ISSUE TITLE
Performance overhead to get Rust primitive values

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#58]
It looks like all values go through the `Value` trait. This adds significant indirection when the common case will be to pass Rust primitives. I wonder what the performance impact of doing this will be compared to special casing Rust primitives.

For example, an event that includes a data field including the size in bytes and an event subscriber that wishes to count the total amount of bytes seen. What is the cost of indirection in this case?

**Comment by hawkw** [comment]
This is a good point --- even if the trait-object based value API remains, it's probably worthwhile to look at optimizing the common case of Rust primitive types. That said, I'm looking into the possibility of replacing this API with something else.
