### ISSUE TITLE
bikeshed: `add_prior_span`

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#59]
Could you elaborate on the name choice? My choice of "follows_from" was copied from open tracing. My initial read of "prior" was temporal vs. causal.

**Comment by hawkw** [comment]
@davidbarsky and I bikeshedded over this naming a bit in https://github.com/hawkw/tokio-trace-prototype/pull/49#discussion_r228199009. Personally, I'm fine with either naming, and am happy to change it back.

**Comment by carllerche** [comment]
I'm not attached to `follows_from`, however I do think it better conveys causality vs. temporal.

There will be many spans that happen before / prior to others. These will not be annotated as such. The only spans to get annotated w/ `follows_from` / `add_prior_span` are spans that are somehow causally related.

**Comment by hawkw** [comment]
> There will be many spans that happen before / prior to others. These will not be annotated as such. The only spans to get annotated w/ `follows_from` / `add_prior_span` are spans that are somehow causally related.

Yeah, you're right --- I agree that `follows_from` better conveys the causal relationship. @davidbarsky, do you have a problem with changing the naming back?
