### ISSUE TITLE
Improve span callsite cache

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#61]
For each span, a subscriber should be able to indicate:

* Always interested
* Never interested
* Sometimes interested

When a subscriber indicates that it is never interested in a span, the instrumentation overhead should not be measurable.

"Sometimes interested" supports the case of sampled instrumentation. The subscriber should be able to efficiently be able to sample traces.

**Comment by carllerche** [comment]
All of this logic should be as encapsulated as possible in -core.

**Comment by hawkw** [comment]
> "Sometimes interested" supports the case of sampled instrumentation. The subscriber should be able to efficiently be able to sample traces.

I was originally expecting sampling to be implemented as part of the filtering API --- a filter could increment a counter and return `true` for every _n_th time that counter is incremented. I think it's possible to move that to the callsite, though that would complicate the filter API a bit. Filters would now have to return something like:
```rust
pub enum Interest {
    Disabled,
    Always,
    SampleEvery(usize),
}
```
The call site could then be responsible for the sampling, and the filter only has to be called once. This does add additional complexity to the callsite cache and to filter implementations. What do you think?

> All of this logic should be as encapsulated as possible in -core.

I agree. Currently the callsite cache is implemented using a macro, which AFAIK is the most performant way to implement something like this --- not using a macro to generate the cache code _at_ the callsite would imply a global hash map of all callsites, or something similar, which I think would add a lot of overhead. Given that, is it okay for the call-site cache macro to remain in `-core` even if we move the `span!`/`event!` macros to a different crate (https://github.com/hawkw/tokio-trace-prototype/issues/23#issuecomment-434401131)?
