### ISSUE TITLE
Is `AsId` necessary in -core?

### ISSUE THREAD

**Issue by carllerche** [hawkw/tokio-trace-prototype#79]
In general, we should stick to fewer traits in -core. Is the `AsId` trait necessary for `-core` to provide the required functionality?

**Comment by hawkw** [comment]
This is probably not necessary in `-core`. It was added to provide a more ergonomic API, but I think it can be moved out of `-core`, similar to `AsKey`. Alternatively, I think this particular trait can just be replaced with `Into<Option<Id>>`...

**Comment by carllerche** [comment]
I would recommend just taking `Id` directly in -core. In theory, it will rarely be used directly.
